### PR TITLE
Implement blink detection clicking and draw Joystick mode eye boxes

### PR DESCRIPTION
**Pull request by Scoobydoo181**
Blink detection clicking is working successfully. Long, slow, and deliberate blinks will successfully click the mouse. I also added a `setMinBlinkDuration()` method to the `EyeDetection` class to allow setting the number of eyeless frames before it detects a blink. Currently, it defaults to 40 frames, which works well for extremely long and deliberate blinks.

I also added support for drawing rectangles to the live camera preview showing where the eyes can move in and out of in order to move the mouse in Joystick mode. Keeping one or both eyes inside the box won't move the mouse, moving both eyes to the left of the box will move the mouse left, moving both eyes above the box will move the mouse up, moving both eyes below the box will move the mouse down, etc.

### CODE REVIEW

**Review by zacowan — CHANGES_REQUESTED** [review]
Wasn't able to get this working so I can test it. After running initial calibration, I got the following error:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/zacowan/.pyenv/versions/3.9.13/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/Users/zacowan/.pyenv/versions/3.9.13/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/zacowan/Development/Senior-Project-Fall-2022/IrisSoftware/main.py", line 242, in processing
    topLeft, bottomRight = self.interpolator.getLeftEyeBox()
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by Scoobydoo181** [comment]
> Wasn't able to get this working so I can test it. After running initial calibration, I got the following error:
> 
> ```
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/Users/zacowan/.pyenv/versions/3.9.13/lib/python3.9/threading.py", line 980, in _bootstrap_inner
>     self.run()
>   File "/Users/zacowan/.pyenv/versions/3.9.13/lib/python3.9/threading.py", line 917, in run
>     self._target(*self._args, **self._kwargs)
>   File "/Users/zacowan/Development/Senior-Project-Fall-2022/IrisSoftware/main.py", line 242, in processing
>     topLeft, bottomRight = self.interpolator.getLeftEyeBox()
> TypeError: cannot unpack non-iterable NoneType object
> ```

That's the code that draws the boxes around your eyes in the live preview. Ah, I see the issue. The only way that error could happen is if `self.state.interpolationType` is set to `InterpolationType.JOYSTICK`, but somehow `InterpolationType.JOYSTICK` never got passed to `interpolator.calibrateInterpolator()`. The variable gets passed in correctly in the `IrisSoftware` constructor, but somehow there's another call to `calibrateInterpolator()` in the `run()` method that never passes in the interpolator type. It looks like that code only runs when you launch the program with no calibration data saved already. I pushed a fix. 

While I was at it, I noticed that the program never re-calibrates the interpolator if the user clicks "calibrate" while the program is running. I pushed a fix for that too.

**Review by zacowan — COMMENTED** [review]
Will probably need to add some guards to prevent the mouse from being moved off-screen. When I ran this again and opened my eyes wide, I got this error again from earlier when we were testing mouse movement:

```
pyautogui.FailSafeException: PyAutoGUI fail-safe triggered from mouse moving to a corner of the screen. To disable this fail-safe, set pyautogui.FAILSAFE to False. DISABLING FAIL-SAFE IS NOT RECOMMENDED.
```

Also, is this what the rectangles for each eye are supposed to look like? It might be worth experimenting a bit more with how to portray this, because it's a little jarring to the eye. Would it be possible to have 1 big rectangle that we move out of to move? Or perhaps having 4 "arrows" that we could move our eyes to in order to move the mouse? Not sure - any ideas?
Screenshot 2022-11-01 at 8 25 19 PM

**Comment by Scoobydoo181** [comment]
> Will probably need to add some guards to prevent the mouse from being moved off-screen. When I ran this again and opened my eyes wide, I got this error again from earlier when we were testing mouse movement:
> 
> ```
> pyautogui.FailSafeException: PyAutoGUI fail-safe triggered from mouse moving to a corner of the screen. To disable this fail-safe, set pyautogui.FAILSAFE to False. DISABLING FAIL-SAFE IS NOT RECOMMENDED.
> ```
> 
> Also, is this what the rectangles for each eye are supposed to look like? It might be worth experimenting a bit more with how to portray this, because it's a little jarring to the eye. Would it be possible to have 1 big rectangle that we move out of to move? Or perhaps having 4 "arrows" that we could move our eyes to in order to move the mouse? Not sure - any ideas? Screenshot 2022-11-01 at 8 25 19 PM

That's really weird, because mine _does_ have one big rectangle
image

**Comment by Scoobydoo181** [comment]
The rectangles are supposed to be the furthest extent of each eye in each direction during calibration. The left edge is the average x position of each eye when looking at the 5 circles on the left edge of the screen during calibration. The top edge is the average y position each eye when looking at the 5 circles on the top edge of the screen during calibration, and so on. The values are calculated by sorting the calibration data points, then averaging together the $\sqrt{\texttt{length}}$ largest and smallest data points.

**Comment by Scoobydoo181** [comment]
And I'm not sure why you're getting corner-of-the screen errors, because Joystick mode moves the mouse exponentially slower the closer you get to the edge of the screen. Are you sure your code isn't using one of the other interpolation models by mistake?

**Comment by zacowan** [comment]
> And I'm not sure why you're getting corner-of-the screen errors, because Joystick mode moves the mouse exponentially slower the closer you get to the edge of the screen. Are you sure your code isn't using one of the other interpolation models by mistake?

Yeah, I've pulled directly from the eyeDetection branch and just ran that branch. And yeah not sure why it did that, but it did pretty quickly 😅

**Comment by Scoobydoo181** [comment]
> > And I'm not sure why you're getting corner-of-the screen errors, because Joystick mode moves the mouse exponentially slower the closer you get to the edge of the screen. Are you sure your code isn't using one of the other interpolation models by mistake?
> 
> Yeah, I've pulled directly from the eyeDetection branch and just ran that branch. And yeah not sure why it did that, but it did pretty quickly 😅

When you pulled from eyeDetection, did it pull the commits onto a branch with existing local changes? Those might interfere with the new changes to cause that behavior

**Comment by zacowan** [comment]
> > > And I'm not sure why you're getting corner-of-the screen errors, because Joystick mode moves the mouse exponentially slower the closer you get to the edge of the screen. Are you sure your code isn't using one of the other interpolation models by mistake?
> > 
> > 
> > Yeah, I've pulled directly from the eyeDetection branch and just ran that branch. And yeah not sure why it did that, but it did pretty quickly 😅
> 
> When you pulled from eyeDetection, did it pull the commits onto a branch with existing local changes? Those might interfere with the new changes to cause that behavior

Nope, I'm just running the eyeDetection branch directly. No other changes

**Comment by Scoobydoo181** [comment]
> > > > And I'm not sure why you're getting corner-of-the screen errors, because Joystick mode moves the mouse exponentially slower the closer you get to the edge of the screen. Are you sure your code isn't using one of the other interpolation models by mistake?
> > > 
> > > 
> > > Yeah, I've pulled directly from the eyeDetection branch and just ran that branch. And yeah not sure why it did that, but it did pretty quickly 😅
> > 
> > 
> > When you pulled from eyeDetection, did it pull the commits onto a branch with existing local changes? Those might interfere with the new changes to cause that behavior
> 
> Nope, I'm just running the eyeDetection branch directly. No other changes

Man, I don't know how it's possible for us to be running the exact same code, but you're getting behavior that should be impossible.
image
If JoystickInterpolator is running, then it only moves towards the maximum coordinates of each edge, and since the circles aren't on the exact edge of the screen, the calibration data doesn't even span the entire display -- it stops a bit before each edge. And since `moveMouse()` always moves 10% of the way from the current cursor position to the target position (which for JoystickInterpolator, is always on the edge of the screen), it should be impossible for the cursor to ever actually reach the edge of the screen, since the distance keeps decreasing as the mouse moves and it always moves 10% of the current distance.

**Comment by zacowan** [comment]
> > > > > And I'm not sure why you're getting corner-of-the screen errors, because Joystick mode moves the mouse exponentially slower the closer you get to the edge of the screen. Are you sure your code isn't using one of the other interpolation models by mistake?
> > > > 
> > > > 
> > > > Yeah, I've pulled directly from the eyeDetection branch and just ran that branch. And yeah not sure why it did that, but it did pretty quickly 😅
> > > 
> > > 
> > > When you pulled from eyeDetection, did it pull the commits onto a branch with existing local changes? Those might interfere with the new changes to cause that behavior
> > 
> > 
> > Nope, I'm just running the eyeDetection branch directly. No other changes
> 
> Man, I don't know how it's possible for us to be running the exact same code, but you're getting behavior that should be impossible. image If JoystickInterpolator is running, then it only moves towards the maximum coordinates of each edge, and since the circles aren't on the exact edge of the screen, the calibration data doesn't even span the entire display -- it stops a bit before each edge. And since `moveMouse()` always moves 10% of the way from the current cursor position to the target position (which for JoystickInterpolator, is always on the edge of the screen), it should be impossible for the cursor to ever actually reach the edge of the screen, since the distance keeps decreasing as the mouse moves and it always moves 10% of the current distance.

Just tried testing a few more times and it looks like this only happens if you move the cursor with your trackpack/mouse. I must have accidentally hit it when I ran it the first time 😅

**Comment by NalinGHub** [comment]
> > Wasn't able to get this working so I can test it. After running initial calibration, I got the following error:
> > ```
> > Exception in thread Thread-1:
> > Traceback (most recent call last):
> >   File "/Users/zacowan/.pyenv/versions/3.9.13/lib/python3.9/threading.py", line 980, in _bootstrap_inner
> >     self.run()
> >   File "/Users/zacowan/.pyenv/versions/3.9.13/lib/python3.9/threading.py", line 917, in run
> >     self._target(*self._args, **self._kwargs)
> >   File "/Users/zacowan/Development/Senior-Project-Fall-2022/IrisSoftware/main.py", line 242, in processing
> >     topLeft, bottomRight = self.interpolator.getLeftEyeBox()
> > TypeError: cannot unpack non-iterable NoneType object
> > ```
> 
> That's the code that draws the boxes around your eyes in the live preview. Ah, I see the issue. The only way that error could happen is if `self.state.interpolationType` is set to `InterpolationType.JOYSTICK`, but somehow `InterpolationType.JOYSTICK` never got passed to `interpolator.calibrateInterpolator()`. The variable gets passed in correctly in the `IrisSoftware` constructor, but somehow there's another call to `calibrateInterpolator()` in the `run()` method that never passes in the interpolator type. It looks like that code only runs when you launch the program with no calibration data saved already. I pushed a fix.
> 
> While I was at it, I noticed that the program never re-calibrates the interpolator if the user clicks "calibrate" while the program is running. I pushed a fix for that too.

I was testing the re-calibration when the program is running and I ran into an error with crashing the processing thread with the eye detection loop.
image

Not exactly sure why the error is happening (tried searching it up, likely something to do with the frame not getting captured correctly?), but I figure that since captureCalibrationEyeCoords() is using detectEyes as well, we don't need to be running detectEyes in the processing thread during any calibration. I'm adding a quick fix to this by just adding another state variable, but there is some improvement that can be made as noted in one of my comments.

edit: might also want to add a sleep for the thread (maybe like 1s at a time) before the continue statement so that the processing thread isn't just continually executing the while->continue->while->continue loop

**Comment by NalinGHub** [comment]
I realize that this sort of disables any mouse control through the program during calibration, so a user may not be able to exit the calibration using their cursor controlled by their eyes anymore. However, since we're assuming that the user is pressing space to perform the calibration, I think it's also a safe assumption that they can exist the calibration by exiting the window with their keyboard (e.g. alt-f4). Thoughts?

**Comment by zacowan** [comment]
> I realize that this sort of disables any mouse control through the program during calibration, so a user may not be able to exit the calibration using their cursor controlled by their eyes anymore. However, since we're assuming that the user is pressing space to perform the calibration, I think it's also a safe assumption that they can exist the calibration by exiting the window with their keyboard (e.g. alt-f4). Thoughts?

I believe you can just press the escape key at any time during calibration and that will exit calibration

**Review by zacowan — APPROVED** [review]
Should be good based on the recent changes.

**Pull request merged**
