### PR TITLE
Added left-right eye ordering unit test

### PR DESCRIPTION
**Pull request by Scoobydoo181**
This test case asserts that the first returned pupil always has a smaller x coordinate than the second returned pupil. This tests that the left and right eyes are always returned in the same order each time.

### CODE REVIEW

**Review by zacowan — CHANGES_REQUESTED** [review]
Can we refactor this to use the [Python unittest library](https://docs.python.org/3/library/unittest.html)? I think it would be useful to decouple our application code from our test code and make it easy to run. Creating a `tests/` directory outside of `IrisSoftware`, and then dedicating a file to each of our modularized portions would make it a little easier to distinguish between tests and application code. Would also make it super easy to demo. All we'd have to do is run the provided unittest command and it would output the results!

**Comment by Scoobydoo181** [comment]
The main problem with that, is that there are no results to output. The inaccurate nature of ML models means that we can't write unit tests for the camera-to-screen conversion code, since there's no predefined input and output to compare. The same thing applies to the pupil detection code, since we can't just pass a test input and assert that it equals the desired output, since a "correct" pupil detection could return potentially hundreds of slightly different values for the same input. The UI code is also impossible to unit test, since it's essentially a large state machine that doesn't just transform input into output.

The tests we have now essentially just isolate a particular part of the ML pipeline and display it for visual inspection by the user. The tests for camera-to-screen conversion isolate the calibration data and graph in by eye and axis. The tests for pupil detection isolate individual steps in the pipeline and visualize them for the user, blob detection, eye detection, pupil, detection, and so on.

So since we don't/can't use unit tests, and instead use more visualization and isolation-focused integration or end-to-end tests, it doesn't make sense to add on a whole unit testing library.

**Comment by zacowan** [comment]
> The main problem with that, is that there are no results to output. The inaccurate nature of ML models means that we can't write unit tests for the camera-to-screen conversion code, since there's no predefined input and output to compare. The same thing applies to the pupil detection code, since we can't just pass a test input and assert that it equals the desired output, since a "correct" pupil detection could return potentially hundreds of slightly different values for the same input. The UI code is also impossible to unit test, since it's essentially a large state machine that doesn't just transform input into output.
> 
> 
> 
> The tests we have now essentially just isolate a particular part of the ML pipeline and display it for visual inspection by the user. The tests for camera-to-screen conversion isolate the calibration data and graph in by eye and axis. The tests for pupil detection isolate individual steps in the pipeline and visualize them for the user, blob detection, eye detection, pupil, detection, and so on.
> 
> 
> 
> So since we don't/can't use unit tests, and instead use more visualization and isolation-focused integration or end-to-end tests, it doesn't make sense to add on a whole unit testing library.

Oh I see what you mean, that makes sense. In that case, looks good 😁

**Review by zacowan — APPROVED** [review]

**Comment by NalinGHub** [comment]
> The main problem with that, is that there are no results to output. The inaccurate nature of ML models means that we can't write unit tests for the camera-to-screen conversion code, since there's no predefined input and output to compare. The same thing applies to the pupil detection code, since we can't just pass a test input and assert that it equals the desired output, since a "correct" pupil detection could return potentially hundreds of slightly different values for the same input. The UI code is also impossible to unit test, since it's essentially a large state machine that doesn't just transform input into output.
> 
> The tests we have now essentially just isolate a particular part of the ML pipeline and display it for visual inspection by the user. The tests for camera-to-screen conversion isolate the calibration data and graph in by eye and axis. The tests for pupil detection isolate individual steps in the pipeline and visualize them for the user, blob detection, eye detection, pupil, detection, and so on.
> 
> So since we don't/can't use unit tests, and instead use more visualization and isolation-focused integration or end-to-end tests, it doesn't make sense to add on a whole unit testing library.

Generally, yes? But also for the test added in this PR it could definitely be placed in an isolated unit test fashion. However, I get what you're saying overall and I'm fine with either approach!

**Pull request merged**
